# Generated by Django 4.1.5 on 2023-04-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('county', models.CharField(choices=[('DE', 'Delaware'), ('K', 'Kent'), ('S', 'Sussex'), ('NC', 'New Castle')], max_length=2)),
                ('categories', models.CharField(max_length=100)),
                ('contact_num', models.CharField(max_length=15)),
                ('contact_urls', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1300)),
            ],
        ),
    ]
