# Generated by Django 4.1.5 on 2023-04-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='contact_num',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='resource',
            name='contact_urls',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
